---
apiVersion: v1
kind: Service
metadata:
  name: lago-api
spec:
  selector:
    app: lago-api
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lago-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lago-api
  template:
    metadata:
      labels:
        app: lago-api
    spec:
      containers:
        - name: lago-api
          image: getlago/lago:latest
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: production
            - name: DATABASE_URL
              value: postgres://lago:lago@postgres:5432/lago_production
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: lago-secrets
                  key: secret-key-base
---
apiVersion: v1
kind: Secret
metadata:
  name: lago-secrets
type: Opaque
data:
  secret-key-base: bGFnby1zZWNyZXQ=  # Base64 encoded string, e.g., `echo -n "lago-secret" | base64`

